on: [push, pull_request]
      

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules

      - name: Install packages
        run: npm install

      - name: Lint files
        run: npm run lint

      - name: Unit tests
        run: npm run test