on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules

      - name: Install packages
        run: yarn install

      - name: Lint files
        run: yarn run lint

      - name: Unit tests
        run: yarn run test